spring.application.name=hexagonal-api
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase

spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
